name: testbench-quarto-gha
channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.11
  - pip
  - ipykernel
  # --- reporting ---
  - marimo
  - jupyterlab
  - jupyter_bokeh
  - nbformat
  - markdownify
  - plotly
  - python-kaleido
  - panel
  # --- data science ---
  - polars
  # --- http ---
  - requests
  - tenacity
  # --- utils ---
  - boltons
  - returns
  - loguru
