[project]
name = "testbench-quarto-gha"
version = "0.1.0"
description = "Add a short description here"
authors = ["yhori <yhori991@gmail.com>"]
channels = ["conda-forge", "main", "r", "msys2"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.11"
pip = ">=24.0,<25"
ipykernel = ">=6.29.4,<6.30"
quarto = ">=1.4.550,<1.5"
polars = ">=0.20.31,<0.21"
plotly = ">=5.22.0,<5.23"
panel = ">=1.4.4,<1.5"
markdownify = ">=0.11.6,<0.12"
jupyterlab = ">=4.2.2,<4.3"
jupyter_bokeh = ">=4.0.5,<4.1"
nbformat = ">=5.10.4,<5.11"
python-kaleido = ">=0.2.1,<0.3"
requests = ">=2.32.3,<2.33"
tenacity = ">=8.4.1,<8.5"
boltons = ">=24.0.0,<24.1"
returns = ">=0.23.0,<0.24"
loguru = ">=0.7.2,<0.8"
marimo = ">=0.6.22,<0.7"
