[project]
name = "testbench-quarto-gha"
version = "0.1.0"
description = "Add a short description here"
authors = ["yhori <yhori991@gmail.com>"]
channels = ["conda-forge", "main", "r", "msys2"]
platforms = ["linux-64"]

[tasks]

[dependencies]

[target.linux-64.dependencies]
python = "==3.11"
pip = "*"
ipykernel = "*"
marimo = "*"
jupyterlab = "*"
jupyter_bokeh = "*"
nbformat = "*"
markdownify = "*"
plotly = "*"
python-kaleido = "*"
panel = "*"
polars = "*"
requests = "*"
tenacity = "*"
boltons = "*"
returns = "*"
loguru = "*"
