project:
  type: website
  preview:
    port: 8000
website:
  title: "hello-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css
execute:
  freeze: auto
